db:
  type: mariadb:10.4
  disk: 2048

cache:
   type: redis:5.0

# The name of the service container. Must be unique within a project.
varnish:
    type: varnish:<VERSION>
    relationships:
        varnish:
            service: app
            endpoint: http
    configuration:
        vcl: !include
            type: string
            path: config.vcl
